package ch08;

public class ExceptionTest {

	public static void main(String[] args) {
		System.out.println(args[0]);	//컴파일에러는 발생하지 않지만 런타임에러가 발생한다.
	}

}
